version: "3.3"

services:
  app:
    build: .
    restart: always
    networks:
      - https-proxy
    expose:
      - "1337"
    environment:
      - VIRTUAL_HOST=
      - LETSENCRYPT_HOST=api.turboapi.dev
      - LETSENCRYPT_EMAIL=josh@turboapi.dev
      - VIRTUAL_PORT=8080

networks:
  https-proxy:
    external:
      name: https-proxy
