version: "3.3"

services:
  app:
    build: .
    restart: always
    networks:
      - https-proxy
    environment:
      - VIRTUAL_HOST=place.dog,dogs.ghent.cloud
      - LETSENCRYPT_HOST=place.dog,dogs.ghent.cloud
      - LETSENCRYPT_EMAIL=josh@turboapi.dev
      - VIRTUAL_PORT=8080

networks:
  https-proxy:
    external:
      name: https-proxy
