version: "3.3"

services:
  app:
    build: .
    restart: unless-stopped
    expose:
      - "8033"
    networks:
      - https-proxy
    volumes:
      - $PWD/.cache:/app/.cache
    environment:
      - VIRTUAL_HOST=place.dog,dogs.ghent.cloud
      - LETSENCRYPT_HOST=place.dog,dogs.ghent.cloud
      - LETSENCRYPT_EMAIL=josh@turboapi.dev
      - VIRTUAL_PORT=8033
    ports:
      - "8033:8033"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8033/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  https-proxy:
    external:
      name: https-proxy
