# fly.toml app configuration file generated for placedog on 2023-05-08T22:11:20+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "placedog"
primary_region = "lhr"

[http_service]
  internal_port = 8033
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[mounts]
source="placedog_img_cache"
destination="/.cache"
