name: Test & Lint

on: [pull_request]

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Install
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Build Server
        run: yarn run build:server

      - name: Build Client
        run: yarn run build
